package com.example.mylibrary

import kotlin.random.Random

class BruceLeeQuotes {
    private val bruceLeeQuotes = listOf(
        "I fear not the man who has practiced 10,000 kicks once, but I fear the man who has practiced one kick 10,000 times.",
        "Empty your mind, be formless, shapeless, like water.",
        "If you spend too much time thinking about a thing, you'll never get it done.",
        "Mistakes are always forgivable if one has the courage to admit them.",
        "The successful warrior is the average man, with laser-like focus.",
        "A goal is not always meant to be reached; it often serves simply as something to aim at.",
        "Don't pray for an easy life, pray for the strength to endure a difficult one.",
        "Knowing is not enough, we must apply. Willing is not enough, we must do.",
        "To hell with circumstances; I create opportunities.",
        "In great attempts, it is glorious even to fail.",
        "The key to immortality is first living a life worth remembering.",
        "The more we value things, the less we value ourselves.",
        "Real living is living for others.",
        "Showing off is the fool's idea of glory.",
        "The doubters said, 'Man cannot fly,' The doers said, 'Maybe, but we'll try,' And finally soared in the morning glow while non-believers watched from below.",
        "A wise man can learn more from his enemies than a fool from his friends.",
        "Do not pray for an easy life, pray for the strength to endure a difficult one.",
        "Life’s battles don’t always go to the stronger or faster man. But sooner or later the man who wins, is the man who thinks he can.",
        "To know oneself is to study oneself in action with another person.",
        "Adapt what is useful, reject what is useless, and add what is specifically your own.",
        "Be like water making its way through cracks. Do not be assertive, but adjust to the object, and you shall find a way around or through it.",
        "Simplicity is the key to brilliance.",
        "The more you value things, the less you value yourself.",
        "A quick temper will make a fool of you soon enough.",
        "A goal is not always meant to be reached; it often serves simply as something to aim at.",
        "Defeat is a state of mind; no one is ever defeated until defeat has been accepted as a reality.",
        "I’m not in this world to live up to your expectations and you’re not in this world to live up to mine.",
        "Knowledge will give you power, but character respect.",
        "If you always put limits on everything you do, physical or anything else, it will spread into your work and into your life. There are no limits. There are only plateaus, and you must not stay there, you must go beyond them.",
        "A wise man can learn more from his enemies than a fool from his friends.",
        "Man, the living creature, the creating individual, is always more important than any established style or system.",
        "The less effort, the faster and more powerful you will be.",
        "Don't get set into one form, adapt it and build your own, and let it grow, be like water.",
        "It’s not the daily increase but daily decrease. Hack away at the unessential.",
        "Showing off is the fool’s idea of glory.",
        "The key to immortality is first living a life worth remembering.",
        "If you love life, don’t waste time, for time is what life is made up of.",
        "As you think, so shall you become.",
        "Don’t fear failure. Not failure, but low aim, is the crime. In great attempts, it is glorious even to fail.",
        "The will to win, the desire to succeed, the urge to reach your full potential… these are the keys that will unlock the door to personal excellence.",
        "Preparation for tomorrow is hard work today.",
        "Knowing is not enough; we must apply. Willing is not enough; we must do.",
        "Notice that the stiffest tree is most easily cracked, while the bamboo or willow survives by bending with the wind.",
        "A goal is not always meant to be reached; it often serves simply as something to aim at.",
        "I’m not in this world to live up to your expectations and you’re not in this world to live up to mine.",
        "Do not pray for an easy life, pray for the strength to endure a difficult one.",
        "To hell with circumstances; I create opportunities.",
        "If you always put limits on everything you do, physical or anything else, it will spread into your work and into your life. There are no limits. There are only plateaus, and you must not stay there, you must go beyond them.",
        "A quick temper will make a fool of you soon enough.",
        "Be happy, but never satisfied.",
        "You just wait. I'm going to be the biggest Chinese Star in the world.",
        "All fixed set patterns are incapable of adaptability or pliability. The truth is outside of all fixed patterns.",
        "Don't get set into one form, adapt it and build your own, and let it grow, be like water. Empty your mind, be formless, shapeless like water. If you put water in the cup it becomes the cup, and water can flow or can crash. Be water, my friend.",
        "The key to immortality is first living a life worth remembering.",
        "If you think a thing is impossible, you'll only make it impossible.",
        "Remember no man is really defeated unless he is discouraged.",
        "The martial arts are ultimately self-knowledge. A punch or a kick is not to knock the hell out of the guy in front, but to knock the hell out of your ego, your fear, or your hang-ups.",
        "I’m not in this world to live up to your expectations and you’re not in this world to live up to mine.",
        "In order to taste my cup of water you must first empty your cup.",
        "The key to immortality is first living a life worth remembering.",
        "Be happy, but never satisfied.",
        "I am learning to understand rather than immediately judge or to be judged. I cannot blindly follow the crowd and accept their approach. I will not allow myself to indulge in the usual manipulating game of role creation. Fortunately for me, my self-knowledge has transcended that and I have come to understand that life is best to be lived and not to be conceptualized. I am happy because I am growing daily and I am honestly not knowing where the limit lies. To be certain, every day there can be a revelation or a new discovery. I treasure the memory of the past misfortunes. It has added more to my bank of fortitude.",
        "To me, the extraordinary aspect of martial arts lies in its simplicity. The easy way is also the right way, and martial arts is nothing at all special; the closer to the true way of martial arts, the less wastage of expression there is.",
        "The possession of anything begins in the mind.",
        "The knowledge and skills you have achieved are meant to be forgotten so you can float comfortably in emptiness, without obstruction.",
        "Knowing is not enough, we must apply. Willing is not enough, we must do.",
        "It is not a daily increase, but a daily decrease. Hack away at the inessentials.",
        "To spend time is to pass it in a specific manner. To waste time is to expend it thoughtlessly or carelessly. We all have time to either spend or waste and it is our decision what to do with it. But once passed, it is gone forever.",
        "Don't get set into one form, adapt it and build your own, and let it grow, be like water. Empty your mind, be formless, shapeless like water. If you put water in the cup it becomes the cup, and water can flow or can crash. Be water, my friend.",
        "Real living is living for others.",
        "The great mistake is to anticipate the outcome of the engagement; you ought not to be thinking of whether it ends in victory or defeat. Let nature take its course, and your tools will strike at the right moment.",
        "Take no thought of who is right or wrong or who is better than. Be not for or against.",
        "A goal is not always meant to be reached, it often serves simply as something to aim at.",
        "The less effort, the faster and more powerful you will be.",
        "It's not the daily increase but daily decrease. Hack away at the unessential.",
        "Notice that the stiffest tree is most easily cracked, while the bamboo or willow survives by bending with the wind.",
        "As you think, so shall you become.",
        "The successful warrior is the average man, with laser-like focus.",
        "To know oneself is to study oneself in action with another person.",
        "As you think, so shall you become.",
        "Don’t fear failure. Not failure, but low aim, is the crime. In great attempts, it is glorious even to fail.",
        "Adapt what is useful, reject what is useless, and add what is specifically your own.",
        "The spirit of the individual is determined by his dominating thought habits.",
        "The less effort, the faster and more powerful you will be.",
        "Real living is living for others.",
        "Do not be tense, just be ready, not thinking but not dreaming, not being set but being flexible. It is being 'wholly' and quietly alive, aware and alert, ready for whatever may come.",
        "The possession of anything begins in the mind.",
        "The martial arts are ultimately self-knowledge. A punch or a kick is not to knock the hell out of the guy in front, but to knock the hell out of your ego, your fear, or your hang-ups.",
        "Knowing is not enough; we must apply. Willing is not enough; we must do.",
        "Notice that the stiffest tree is most easily cracked, while the bamboo or willow survives by bending with the wind.",
        "If you always put limits on everything you do, physical or anything else, it will spread into your work and into your life. There are no limits. There are only plateaus, and you must not stay there, you must go beyond them.",
        "Using no way as a way, having no limitation as limitation.",
        "I’m not in this world to live up to your expectations and you’re not in this world to live up to mine.",
        "The height of cultivation runs to simplicity.",
        "Do not pray for an easy life, pray for the strength to endure a difficult one.",
        "Adapt what is useful, reject what is useless, and add what is specifically your own.",
        "To hell with circumstances; I create opportunities.",
        "As you think, so shall you become.",
        "Real living is living for others.",
        "A quick temper will make a fool of you soon enough.",
        "Don’t fear failure. Not failure, but low aim, is the crime. In great attempts, it is glorious even to fail.",
        "The great mistake is to anticipate the outcome of the engagement; you ought not to be thinking of whether it ends in victory or defeat. Let nature take its course, and your tools will strike at the right moment.",
        "Showing off is the fool’s idea of glory.",
        "The key to immortality is first living a life worth remembering.",
        "If you think a thing is impossible, you'll only make it impossible.",
        "The successful warrior is the average man, with laser-like focus.",
        "Preparation for tomorrow is hard work today.",
        "In great attempts, it is glorious even to fail.",
        "To spend time is to pass it in a specific manner. To waste time is to expend it thoughtlessly or carelessly. We all have time to either spend or waste and it is our decision what to do with it. But once passed, it is gone forever.",
        "Knowing is not enough, we must apply. Willing is not enough, we must do.",
        "Knowing is not enough; we must apply. Willing is not enough; we must do.",
        "If you love life, don’t waste time, for time is what life is made up of.",
        "Don’t get set into one form, adapt it and build your own, and let it grow, be like water.",
        "You just wait. I'm going to be the biggest Chinese Star in the world.",
        "All fixed set patterns are incapable of adaptability or pliability. The truth is outside of all fixed patterns.",
        "Don't get set into one form, adapt it and build your own, and let it grow, be like water. Empty your mind, be formless, shapeless like water. If you put water in the cup it becomes the cup, and water can flow or can crash. Be water, my friend.",
        "The key to immortality is first living a life worth remembering.",
        "If you think a thing is impossible, you'll only make it impossible.",
        "Remember no man is really defeated unless he is discouraged.",
        "The martial arts are ultimately self-knowledge. A punch or a kick is not to knock the hell out of the guy in front, but to knock the hell out of your ego, your fear, or your hang-ups.",
        "I’m not in this world to live up to your expectations and you’re not in this world to live up to mine.",
        "In order to taste my cup of water you must first empty your cup.",
        "The key to immortality is first living a life worth remembering.",
        "Be happy, but never satisfied.",
        "I am learning to understand rather than immediately judge or to be judged. I cannot blindly follow the crowd and accept their approach. I will not allow myself to indulge in the usual manipulating game of role creation. Fortunately for me, my self-knowledge has transcended that and I have come to understand that life is best to be lived and not to be conceptualized. I am happy because I am growing daily and I am honestly not knowing where the limit lies. To be certain, every day there can be a revelation or a new discovery. I treasure the memory of the past misfortunes. It has added more to my bank of fortitude.",
        "To me, the extraordinary aspect of martial arts lies in its simplicity. The easy way is also the right way, and martial arts is nothing at all special; the closer to the true way of martial arts, the less wastage of expression there is.",
    )

    fun getRandomBruceLeeQuote(): String {
        val randomIndex = Random.nextInt(bruceLeeQuotes.size)
        return bruceLeeQuotes[randomIndex]
    }
}